name: base_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  mysql1: ^0.20.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

  commons_core:
    path: ./packages/commons/commons-core
  dart_jsonwebtoken: ^2.7.1
  password_dart: ^2.0.1